"""add location_logs table, add lat/lng to drowsiness_events

Revision ID: 2a132fc0b43a
Revises: 74d019bf270a
Create Date: 2026-09-05 18:09:33.722195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2a132fc0b43a'
down_revision: Union[str, Sequence[str], None] = '74d019bf270a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location_logs',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('session_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('device_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('speed_kmh', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('drowsiness_events', sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=True))
    op.add_column('drowsiness_events', sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('drowsiness_events', 'longitude')
    op.drop_column('drowsiness_events', 'latitude')
    op.drop_table('location_logs')
    # ### end Alembic commands ###
