"""add username column to users

Revision ID: 33adc8536c3a
Revises: 875e19781a92
Create Date: 2026-08-22 20:26:10.153317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '33adc8536c3a'
down_revision: Union[str, Sequence[str], None] = '875e19781a92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.alter_column('users', 'full_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               type_=sa.String(length=150),
               existing_nullable=False)
    op.alter_column('users', 'role',
               existing_type=mysql.ENUM('admin', 'driver', collation='utf8mb4_unicode_ci'),
               type_=sa.String(length=30),
               existing_nullable=False)
    op.drop_index(op.f('email'), table_name='users')
    op.create_unique_constraint(None, 'users', ['username'])
    op.create_unique_constraint(None, 'users', ['phone'])
    op.drop_column('users', 'status')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True))
    op.add_column('users', sa.Column('status', mysql.ENUM('active', 'locked', collation='utf8mb4_unicode_ci'), nullable=True))
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index(op.f('email'), 'users', ['email'], unique=True)
    op.alter_column('users', 'role',
               existing_type=sa.String(length=30),
               type_=mysql.ENUM('admin', 'driver', collation='utf8mb4_unicode_ci'),
               existing_nullable=False)
    op.alter_column('users', 'full_name',
               existing_type=sa.String(length=150),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               existing_nullable=False)
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
